# Generated by Django 5.1.2 on 2024-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Media'), ('Alta', 'Alta')], default='Baixa', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='task/img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
